apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-result-app
    name: result-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    app: demo-voting-app
    name: result-app-pod