apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    app: demo-voting-app
    name: worker-pod
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v2
